trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
  - group: JMETER_TERRAFORM_SETTINGS
  - name: JMETER_DIRECTORY_INPUT
    value: $(System.DefaultWorkingDirectory)/perf-testing-scenrios
  - name: JMETER_DIRECTORY_OUTPUT
    value: $(System.DefaultWorkingDirectory)/results
  - name: TERRAFORM_VERSION
    value: 0.13.2

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'f4all.acr'
      command: 'login'
  
  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: 'Paiement à l’utilisation(1ad44334-f828-4bde-a49e-7de4f43ce1ba)'
      scriptType: 'bash'
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
  - task: AzureCLI@2
    displayName: 'SETUP: Validate JMeter Docker Image'
    inputs:
      azureSubscription: 'Paiement à l’utilisation(1ad44334-f828-4bde-a49e-7de4f43ce1ba)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login -n $(TF_VAR_JMETER_ACR_NAME)
        docker login https://f4all.azurecr.io -u $(TF_VAR_ACR_LOGIN) -p $(TF_VAR_ACR_PASS)
        docker pull $(TF_VAR_JMETER_DOCKER_IMAGE)

  - script: |
      docker run --name=jmx-validator -v $(JMETER_DIRECTORY_INPUT):/jmeter -w /jmeter \
        --entrypoint "TestPlanCheck.sh" $(TF_VAR_JMETER_DOCKER_IMAGE) \
        --stats --tree-dump --jmx $(TF_VAR_JMETER_JMX_FILE)
    displayName: 'SETUP: Validate JMX File'
  
  - script: |
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Paiement à l’utilisation(1ad44334-f828-4bde-a49e-7de4f43ce1ba)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az ad sp show --id 296d820d-4bb2-4fd3-89d1-c6c01017d26e
            az vm list
            az role assignment create --assignee "296d820d-4bb2-4fd3-89d1-c6c01017d26e" \
              --role "Load Test Contributor" \
              --scope /subscriptions/1ad44334-f828-4bde-a49e-7de4f43ce1ba/resourceGroups/infra-01_group \
              --subscription 'Paiement à l’utilisation(1ad44334-f828-4bde-a49e-7de4f43ce1ba)'


